In [34]:
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import os

In [36]:
semeval_rest_train = './datasets/semeval14/Restaurants_Train.xml.seg'
semeval_rest_test = './datasets/semeval14/Restaurants_Test_Gold.xml.seg'
semeval_lap_train = './datasets/semeval14/Laptops_Train.xml.seg'
semeval_lap_test =  './datasets/semeval14/Laptops_Test_Gold.xml.seg'
twitter_train = './datasets/acl-14-short-data/train.raw'
twitter_test = './datasets/acl-14-short-data/test.raw'

path_list = [semeval_rest_train,semeval_rest_test,semeval_lap_train,semeval_lap_test,twitter_train,twitter_test]

def transform(path):
    with open(path,'r',encoding='utf-8',newline='\n',errors='ignore') as f:
        line = f.readlines()
    df = pd.DataFrame(columns=['text','aspect','sentiment'])
    for i in range(0,len(line),3):
        text = line[i].strip()
        aspect = line[i+1].strip()
        sentiment = line[i+2].strip()
        df = df.append(pd.Series({'text':text,'aspect':aspect,'sentiment':sentiment}),ignore_index=True)
    if not os.path.exists('dataset_pd'):
        os.mkdir('dataset_pd')
    with open('dataset_pd/'+path.split('/')[-1]+'.pd','w') as f:
        df.to_csv(f,index=False)
for i in path_list:
    transform(i)

In [54]:

file_path = './datasets/semeval14/Restaurants_Train.xml.seg'
def statistic_aspect(path):
    with open(path,'r',encoding='utf-8',newline='\n',errors='ignore') as f:
        line = f.readlines()
    df = pd.DataFrame(columns=['text','aspect','sentiment'])
    for i in range(0,len(line),3):
        text = line[i].strip()
        aspect = line[i+1].strip()
        sentiment = line[i+2].strip()
        df = df.append(pd.Series({'text':text,'aspect':aspect,'sentiment':sentiment}),ignore_index=True)
    df.head()
    df.shape
    r = df['aspect'].map(lambda x:x.lower()).value_counts()
    print(r)
    return r

In [58]:
a = statistic_aspect(file_path)

food                        361
service                     225
prices                       63
place                        59
dinner                       56
menu                         56
staff                        55
pizza                        51
atmosphere                   46
table                        41
price                        41
meal                         40
sushi                        37
drinks                       35
bar                          32
lunch                        29
dishes                       28
portions                     27
waiter                       26
ambience                     26
decor                        25
wine                         24
fish                         22
ambiance                     21
dish                         20
reservation                  19
bagels                       19
dessert                      18
wine list                    18
wait                         18
                           ...
strawberry daiquiries         1
asian appetizers              1
private room                  1
glasses of champagne          1
lobster ravioli               1
cheeseburger                  1
outdoor atmosphere            1
'gourmet' indian cuisine      1
grilled branzino              1
cold lobster salad            1
beverage manager              1
wine by the glass             1
maine lobster                 1
variety of dishes             1
spicy tuna                    1
cold appetizer dishes         1
martinis                      1
bills                         1
sichuan food                  1
insde table                   1
bagel with lox spread         1
in sandwiches                 1
dimsum                        1
fish dishes                   1
fresh tomato sauce            1
spinach mushroom calzone      1
rice congee soup              1
fried clams                   1
pork belly                    1
refleshment                   1
Name: aspect, Length: 1202, dtype: int64

In [59]:
a.value_counts()

1      904
2      123
3       44
5       18
4       18
6       17
9        8
8        7
10       6
14       6
11       5
7        4
12       4
18       4
13       3
56       2
41       2
19       2
26       2
16       2
15       1
17       1
361      1
20       1
225      1
63       1
59       1
55       1
51       1
46       1
40       1
37       1
35       1
32       1
29       1
28       1
27       1
25       1
24       1
22       1
21       1
Name: aspect, dtype: int64

In [41]:
lap_path = './datasets/semeval14/Laptops_Train.xml.seg'
statistic_aspect(lap_path)

screen                          61
price                           56
use                             54
battery life                    53
keyboard                        50
battery                         47
programs                        37
features                        35
software                        33
warranty                        32
hard drive                      30
windows                         30
size                            24
quality                         23
performance                     23
speed                           21
memory                          18
applications                    18
runs                            18
graphics                        17
motherboard                     16
system                          14
vista                           14
windows 7                       14
gaming                          13
charge                          13
program                         13
works                           13
design                          13
keys                            13
                                ..
install                          1
windows vista home premium       1
weighed                          1
performed                        1
trial software                   1
system board                     1
hdd bay                          1
power cords                      1
size of the screen               1
windows xp professional          1
hdmi                             1
responds                         1
norton                           1
shipment                         1
snow leopard x                   1
full charge                      1
typing                           1
osx 16                           1
find files                       1
charger unit                     1
customer service number          1
product and help aftermarket     1
media                            1
toshiba warranty                 1
delivery service                 1
bluray player                    1
costs                            1
photo detection software         1
flexibility                      1
linux based os                   1
Name: aspect, Length: 949, dtype: int64

In [42]:
twitter_path= './datasets/acl-14-short-data/train.raw'
statistic_aspect(twitter_path)

britney spears         924
lindsay lohan          400
harry potter           324
madonna                233
barack obama           222
wii                    195
sarah palin            191
lady gaga              181
ipod                   180
windows 7              171
iphone                 168
lakers                 161
xbox                   160
kindle                 155
justin bieber          142
google wave            140
psp                    129
obama                  126
ipad                   121
google                 117
jimmy carter           101
steve jobs              98
micheal jackson         87
charlie sheen           83
tiger woods             77
nicolas cage            77
hillary clinton         71
hilary swank            70
george bush             64
bill gates              54
                      ...
weird al yankovic        3
shaquille o'neal         2
bieber                   2
barack                   2
miley                    2
chelsea handler          2
tim bresnan              2
johnmayer                1
al-anon mtg              1
britneyspears            1
tony hawk                1
larry king               1
conan o'brien            1
o                        1
mindflex game            1
britney sears            1
kourtney kardashian      1
albert pujols            1
snoop dog                1
elizabeth taylor         1
justin drew bieber       1
stephen fry              1
biden                    1
donald trump             1
j lo                     1
a-rod                    1
miley ray cyrus          1
lance armstrong          1
kevin spacey             1
rev run                  1
Name: aspect, Length: 113, dtype: int64

In [44]:
err_path = 'state_dict/mgan_restaurant_val_acc_err'
err = pd.read_csv(open(err_path,'r'))

In [46]:
err['aspect'].value_counts()

food                               20
menu                               13
service                             7
prices                              5
waiter                              4
dinner                              3
meal                                3
lunch                               3
staff                               3
price                               3
drink                               3
waitress                            3
appetizers                          3
music                               2
atmosphere                          2
steaks                              2
steak                               2
dining experience                   2
served                              2
pizza                               2
decor                               2
drinks                              2
SERVICE                             2
space                               2
sushi                               1
stuffed baked potatoes              1
staff person                        1
Tequila                             1
quality of the meat                 1
sandwiches                          1
                                   ..
sangria                             1
appetizer selection                 1
margarita                           1
meaty chili                         1
fennel flavored Italian sausage     1
spicy cod roe spaghetti             1
dish                                1
appetizer                           1
deserts                             1
bartender                           1
reservation                         1
quality of food                     1
meats                               1
Tables                              1
side orders                         1
duck confitte                       1
Cinna Stix                          1
halibut cheek appetizer             1
delivery times                      1
candlelight                         1
breakfast                           1
FOOD                                1
cajun shrimp                        1
sauce                               1
chicken parmigiana                  1
utensils                            1
chef                                1
egg                                 1
lounge                              1
Indian food                         1
Name: aspect, Length: 183, dtype: int64

In [56]:
r_test_path= './datasets/semeval14/Restaurants_Test_Gold.xml.seg'
r = statistic_aspect(r_test_path)

food                                                          125
service                                                        74
menu                                                           22
staff                                                          21
atmosphere                                                     21
place                                                          19
prices                                                         18
sushi                                                          14
meal                                                           14
waiter                                                         13
drinks                                                         13
price                                                          11
desserts                                                        9
waiters                                                         8
wine                                                            8
lunch                                                           8
pizza                                                           8
dinner                                                          7
chicken                                                         6
priced                                                          6
bartender                                                       6
appetizers                                                      6
indian food                                                     6
salads                                                          6
owner                                                           6
portions                                                        6
entrees                                                         6
decor                                                           5
bar                                                             5
music                                                           5
                                                             ...
soy mayonaise                                                   1
decoration                                                      1
rice milk                                                       1
fettuccine with grilled seafood in a rosemary-orange sauce      1
shepherds pie                                                   1
sliced steak entree                                             1
filet-o-fish sandwich                                           1
folding chair                                                   1
parmesan cheese                                                 1
pasta primavera                                                 1
kimono shrimp special                                           1
[female] servers                                                1
spices                                                          1
afternoon snack                                                 1
saag gosht                                                      1
fried calamari                                                  1
ac                                                              1
malted milk ball gelato                                         1
grand marnier shrimp                                            1
seats                                                           1
appetizer selection                                             1
tequila                                                         1
churrasco                                                       1
french fries                                                    1
fajita                                                          1
disco pop duo                                                   1
new menu                                                        1
greek yogurt (with cuccumber, dill, and garlic)                 1
pizza with soy cheese                                           1
pork product                                                    1
Name: aspect, Length: 520, dtype: int64

In [57]:
r.value_counts()

1      411
2       36
3       22
4       16
6        9
5        8
8        4
21       2
14       2
13       2
7        1
125      1
74       1
11       1
18       1
19       1
22       1
9        1
Name: aspect, dtype: int64

In [51]:
x = err['aspect'].value_counts()

In [53]:
x.value_counts()

1     159
2      11
3       8
20      1
13      1
7       1
5       1
4       1
Name: aspect, dtype: int64

In [60]:
acl_path = 'dataset_pd/train.raw.pd'
with open(acl_path,'r') as f :
    acl_data= pd.read_csv(acl_path)
acl_data.head()

,text,aspect,sentiment
0,"i agree about arafat . i mean , shit , they ev...",jimmy carter,-1
1,musicmonday $T$ - lucky do you remember this s...,britney spears,1
2,"wtf ? $T$ is coming to my school today , just ...",hilary swank,0
3,my 3-year-old was amazed yesterday to find tha...,wii,0
4,God damn . That Sony remote for $T$ is fucking...,google,-1

In [62]:
acl_data['aspect'].value_counts()

britney spears         924
lindsay lohan          400
harry potter           324
madonna                233
barack obama           222
wii                    195
sarah palin            191
lady gaga              181
ipod                   180
windows 7              171
iphone                 168
lakers                 161
xbox                   160
kindle                 155
justin bieber          142
google wave            140
psp                    129
obama                  126
ipad                   121
google                 117
jimmy carter           101
steve jobs              98
micheal jackson         87
charlie sheen           83
tiger woods             77
nicolas cage            77
hillary clinton         71
hilary swank            70
george bush             64
bill gates              54
                      ...
weird al yankovic        3
shaquille o'neal         2
bieber                   2
barack                   2
miley                    2
chelsea handler          2
tim bresnan              2
johnmayer                1
al-anon mtg              1
britneyspears            1
tony hawk                1
larry king               1
conan o'brien            1
o                        1
mindflex game            1
britney sears            1
kourtney kardashian      1
albert pujols            1
snoop dog                1
elizabeth taylor         1
justin drew bieber       1
stephen fry              1
biden                    1
donald trump             1
j lo                     1
a-rod                    1
miley ray cyrus          1
lance armstrong          1
kevin spacey             1
rev run                  1
Name: aspect, Length: 113, dtype: int64